package com.brinks.use_cases.create_new_brazilian_employee_user_request.factories;

import com.brinks.use_cases.contracts.UseCaseFactory;
import com.brinks.use_cases.create_new_brazilian_employee_user_request.CreateNewBrazilianEmployeeUserRequestUseCase;

public interface CreateNewBrazilianEmployeeUserRequestUseCaseFactory extends UseCaseFactory<CreateNewBrazilianEmployeeUserRequestUseCase> {
}
